### ISSUE TITLE
hassio不能运行

### ISSUE THREAD

**Issue by chaoself1985** [shaonianzhentan/ha_qqmail#6]
在hassio里运行不了，不知道是何原因

Logger: homeassistant.components.websocket_api.http.connection
Source: components/hassio/__init__.py:535
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 17:01:19 (1 occurrences)
Last logged: 17:01:19

[547991092288] The system cannot restart because the configuration is not valid: Component error: ha_qqmail - Integration 'ha_qqmail' not found.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 535, in async_handle_core_service
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Component error: ha_qqmail - Integration 'ha_qqmail' not found.

**Comment by shaonianzhentan** [comment]
> 在hassio里运行不了，不知道是何原因
> 
> Logger: homeassistant.components.websocket_api.http.connection
> Source: components/hassio/**init**.py:535
> Integration: Home Assistant WebSocket API (documentation, issues)
> First occurred: 17:01:19 (1 occurrences)
> Last logged: 17:01:19
> 
> [547991092288] The system cannot restart because the configuration is not valid: Component error: ha_qqmail - Integration 'ha_qqmail' not found.
> Traceback (most recent call last):
> File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
> await hass.services.async_call(
> File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
> task.result()
> File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
> await handler.job.target(service_call)
> File "/usr/src/homeassistant/homeassistant/components/hassio/**init**.py", line 535, in async_handle_core_service
> raise HomeAssistantError(
> homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Component error: ha_qqmail - Integration 'ha_qqmail' not found.

这个插件不更新了，换其它的吧
